from __future__ import annotations

import json
import os
import struct
import zlib
from pathlib import Path
from typing import Any
from uuid import UUID

import pytest
from conftest import character, context

from fantareal_mobile_chat.domain import DomainError
from fantareal_mobile_chat.service import MobileChatService

TOKEN = str(UUID("22222222-3333-4444-5555-666666666666"))


def _png_chunk(kind: bytes, payload: bytes) -> bytes:
    checksum = zlib.crc32(kind)
    checksum = zlib.crc32(payload, checksum) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + kind + payload + struct.pack(">I", checksum)


def png_bytes(red: int = 40, green: int = 130, blue: int = 220) -> bytes:
    header = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", 1, 1, 8, 6, 0, 0, 0)
    pixel = zlib.compress(bytes([0, red, green, blue, 255]))
    return header + _png_chunk(b"IHDR", ihdr) + _png_chunk(b"IDAT", pixel) + _png_chunk(
        b"IEND", b""
    )


def manifest(
    *,
    pack_id: str = "com.example.fixture",
    version: str = "1.0.0",
    asset_path: str = "assets/sticker.png",
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    result = {
        "schemaVersion": 1,
        "id": pack_id,
        "name": "自制测试资源",
        "version": version,
        "description": "由测试在临时目录中生成。",
        "license": {
            "name": "Fixture-only",
            "source": "pytest generated bytes",
            "redistributionAllowed": False,
            "attribution": "Fantareal test fixture",
        },
        "assets": [
            {
                "id": "rain-sticker",
                "kind": "sticker",
                "path": asset_path,
                "mediaType": "image/png",
                "alt": "蓝色像素",
            }
        ],
    }
    if extra:
        result.update(extra)
    return result


def make_pack(
    root: Path,
    *,
    pack_id: str = "com.example.fixture",
    version: str = "1.0.0",
    asset_path: str = "assets/sticker.png",
    payload: bytes | None = None,
    extra: dict[str, Any] | None = None,
) -> Path:
    root.mkdir()
    target = root.joinpath(*asset_path.split("/"))
    target.parent.mkdir(parents=True)
    target.write_bytes(payload if payload is not None else png_bytes())
    (root / "resource-pack.json").write_text(
        json.dumps(
            manifest(
                pack_id=pack_id,
                version=version,
                asset_path=asset_path,
                extra=extra,
            )
        ),
        encoding="utf-8",
    )
    return root


def make_mixed_pack(root: Path) -> Path:
    root.mkdir()
    assets = {
        "assets/sticker.png": png_bytes(),
        "assets/background.png": png_bytes(18, 48, 86),
    }
    for relative_path, payload in assets.items():
        target = root.joinpath(*relative_path.split("/"))
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(payload)
    value = manifest()
    value["assets"] = [
        value["assets"][0],
        {
            "id": "night-background",
            "kind": "background",
            "path": "assets/background.png",
            "mediaType": "image/png",
            "alt": "深蓝夜空",
        },
    ]
    (root / "resource-pack.json").write_text(
        json.dumps(value),
        encoding="utf-8",
    )
    return root


def grant(service: MobileChatService, selected: Path, token: str = TOKEN) -> str:
    assert service.store is not None
    grants = service.store.workspace_root / "input-directory-grants"
    grants.mkdir(exist_ok=True)
    (grants / f"{token}.json").write_text(
        json.dumps(
            {
                "kind": "fantareal.directory-grant",
                "schemaVersion": 1,
                "token": token,
                "path": str(selected),
                "name": selected.name,
                "readOnly": True,
            }
        ),
        encoding="utf-8",
    )
    return token


def initialized_service(tmp_path: Path, quota: int) -> MobileChatService:
    tmp_path.mkdir(parents=True, exist_ok=True)
    data = tmp_path / "service-data"
    assets = tmp_path / "service-assets"
    workspace = tmp_path / "service-workspace"
    data.mkdir()
    assets.mkdir()
    workspace.mkdir()
    service = MobileChatService()
    service.dispatch(
        "extension.initialize",
        {
            "workspace": str(workspace),
            "locale": "zh-CN",
            "permissions": ["storage.data", "storage.assets"],
            "storage": {
                "paths": {"data": str(data), "assets": str(assets)},
                "quotas": {"data": 64 * 1024 * 1024, "assets": quota},
            },
        },
    )
    active = character()
    service.dispatch(
        "mobile.context.bind",
        {
            "context": context(),
            "activeCharacter": active,
            "characters": [active],
        },
    )
    return service


def preview(service: MobileChatService, selected: Path) -> dict[str, Any]:
    return service.dispatch(
        "mobile.resources.preview",
        {"context": context(), "directoryToken": grant(service, selected)},
    )


def install(service: MobileChatService, selected: Path) -> dict[str, Any]:
    result = preview(service, selected)
    return service.dispatch(
        "mobile.resources.import",
        {
            "context": context(),
            "directoryToken": TOKEN,
            "contentDigest": result["contentDigest"],
        },
    )["pack"]


def test_preview_import_list_delete_and_per_card_isolation(
    service: MobileChatService,
    tmp_path: Path,
) -> None:
    selected = make_pack(tmp_path / "pack")
    inspected = preview(service, selected)
    assert inspected["license"]["source"] == "pytest generated bytes"
    assert inspected["kindCounts"] == {"sticker": 1}
    assert inspected["fitsQuota"] is True
    assert inspected["previewAssets"][0]["dataUrl"].startswith("data:image/png;base64,")

    installed = service.dispatch(
        "mobile.resources.import",
        {
            "context": context(),
            "directoryToken": TOKEN,
            "contentDigest": inspected["contentDigest"],
        },
    )["pack"]
    assert installed["id"] == "com.example.fixture"
    listed = service.dispatch("mobile.resources.list", {"context": context()})
    assert listed["packs"][0]["status"] == "ready"
    assert listed["packs"][0]["assetCount"] == 1

    bob = character("card_b", "Bob")
    service.dispatch(
        "mobile.context.bind",
        {
            "context": context("card_b", "revision_b"),
            "activeCharacter": bob,
            "characters": [bob],
        },
    )
    assert service.dispatch(
        "mobile.resources.list",
        {"context": context("card_b", "revision_b")},
    )["packs"] == []

    alice = character()
    service.dispatch(
        "mobile.context.bind",
        {
            "context": context(),
            "activeCharacter": alice,
            "characters": [alice],
        },
    )
    deleted = service.dispatch(
        "mobile.resources.delete",
        {"context": context(), "packId": installed["id"]},
    )
    assert deleted["deleted"] is True
    assert service.dispatch("mobile.resources.list", {"context": context()})["packs"] == []


@pytest.mark.parametrize(
    ("mutate", "code"),
    [
        (lambda value: value.update({"unexpected": True}), "resource_pack_invalid"),
        (lambda value: value.pop("license"), "resource_pack_invalid"),
        (
            lambda value: value["assets"][0].update({"path": "assets/../escape.png"}),
            "resource_pack_invalid",
        ),
    ],
)
def test_manifest_is_strict(
    service: MobileChatService,
    tmp_path: Path,
    mutate: Any,
    code: str,
) -> None:
    selected = make_pack(tmp_path / "strict-pack")
    path = selected / "resource-pack.json"
    value = json.loads(path.read_text(encoding="utf-8"))
    mutate(value)
    path.write_text(json.dumps(value), encoding="utf-8")
    with pytest.raises(DomainError) as exc_info:
        preview(service, selected)
    assert exc_info.value.code == code


def test_corrupt_media_and_link_are_rejected(
    service: MobileChatService,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    corrupt = make_pack(tmp_path / "corrupt-pack", payload=b"\x89PNG\r\n\x1a\nbroken")
    with pytest.raises(DomainError) as exc_info:
        preview(service, corrupt)
    assert exc_info.value.code == "resource_pack_corrupt"

    linked = make_pack(tmp_path / "linked-pack")
    linked_asset = linked / "assets" / "sticker.png"
    original = os.fspath(linked_asset)
    from fantareal_mobile_chat import resource_packs

    real_check = resource_packs.is_link_or_reparse
    monkeypatch.setattr(
        resource_packs,
        "is_link_or_reparse",
        lambda path: os.fspath(path) == original or real_check(path),
    )
    with pytest.raises(DomainError) as link_error:
        preview(service, linked)
    assert link_error.value.code == "resource_pack_unsafe"


def test_intermediate_link_or_junction_is_rejected(
    service: MobileChatService,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    selected = make_pack(tmp_path / "linked-parent-pack")
    linked_parent = os.fspath(selected / "assets")
    from fantareal_mobile_chat import resource_packs

    real_check = resource_packs.is_link_or_reparse
    monkeypatch.setattr(
        resource_packs,
        "is_link_or_reparse",
        lambda path: os.fspath(path) == linked_parent or real_check(path),
    )
    with pytest.raises(DomainError) as exc_info:
        preview(service, selected)
    assert exc_info.value.code == "resource_pack_unsafe"


def test_zero_and_insufficient_quota_leave_no_partial_pack(tmp_path: Path) -> None:
    selected = make_pack(tmp_path / "quota-pack")
    zero = initialized_service(tmp_path / "zero", 0)
    inspected = preview(zero, selected)
    assert inspected["fitsQuota"] is False
    with pytest.raises(DomainError) as zero_error:
        install(zero, selected)
    assert zero_error.value.code == "assets_quota_unconfigured"
    assert zero.dispatch("mobile.resources.list", {"context": context()})["packs"] == []

    tiny = initialized_service(tmp_path / "tiny", 8)
    with pytest.raises(DomainError) as tiny_error:
        install(tiny, selected)
    assert tiny_error.value.code == "assets_quota_exceeded"
    assert tiny.dispatch("mobile.resources.list", {"context": context()})["packs"] == []


def test_preview_digest_blocks_changed_source(
    service: MobileChatService,
    tmp_path: Path,
) -> None:
    selected = make_pack(tmp_path / "changing-pack")
    inspected = preview(service, selected)
    (selected / "assets" / "sticker.png").write_bytes(png_bytes(220, 80, 50))
    with pytest.raises(DomainError) as exc_info:
        service.dispatch(
            "mobile.resources.import",
            {
                "context": context(),
                "directoryToken": TOKEN,
                "contentDigest": inspected["contentDigest"],
            },
        )
    assert exc_info.value.code == "resource_pack_changed"
    assert service.dispatch("mobile.resources.list", {"context": context()})["packs"] == []


def test_failed_replacement_restores_previous_pack(
    service: MobileChatService,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    first = make_pack(tmp_path / "first-pack", version="1.0.0")
    install(service, first)
    second = make_pack(
        tmp_path / "second-pack",
        version="2.0.0",
        payload=png_bytes(180, 70, 130),
    )
    inspected = preview(service, second)

    from fantareal_mobile_chat import resource_packs

    real_replace = resource_packs.os.replace

    def fail_stage(source: Any, destination: Any) -> None:
        if str(source).endswith(".stage"):
            raise OSError("fixture swap failure")
        real_replace(source, destination)

    monkeypatch.setattr(resource_packs.os, "replace", fail_stage)
    with pytest.raises(DomainError) as exc_info:
        service.dispatch(
            "mobile.resources.import",
            {
                "context": context(),
                "directoryToken": TOKEN,
                "contentDigest": inspected["contentDigest"],
            },
        )
    assert exc_info.value.code == "storage_write_failed"
    listed = service.dispatch("mobile.resources.list", {"context": context()})
    assert listed["packs"][0]["version"] == "1.0.0"


def test_damaged_installed_pack_does_not_break_text_chat(
    service: MobileChatService,
    tmp_path: Path,
) -> None:
    selected = make_pack(tmp_path / "damage-after-install")
    install(service, selected)
    assert service.resource_packs is not None
    installed = (
        service.resource_packs.assets_root
        / "cards"
        / "card_a"
        / "resource-packs"
        / "com.example.fixture"
        / "resource-pack.json"
    )
    installed.write_text("{broken", encoding="utf-8")
    listed = service.dispatch("mobile.resources.list", {"context": context()})
    assert listed["packs"][0]["status"] == "damaged"
    assert service.dispatch("mobile.groups.list", {"context": context()}) == {"groups": []}
    assert service.dispatch(
        "mobile.resources.delete",
        {"context": context(), "packId": "com.example.fixture"},
    )["deleted"] is True


def test_appearance_is_per_card_and_background_falls_back_after_delete(
    service: MobileChatService,
    tmp_path: Path,
) -> None:
    selected = make_mixed_pack(tmp_path / "mixed-pack")
    install(service, selected)

    updated = service.dispatch(
        "mobile.appearance.update",
        {
            "context": context(),
            "appearance": {
                "preset": "xianxia",
                "tone": "mist",
                "background": {
                    "packId": "com.example.fixture",
                    "assetId": "night-background",
                },
            },
        },
    )
    assert updated["appearance"]["preset"] == "xianxia"
    assert updated["appearance"]["tone"] == "mist"
    assert updated["backgroundAsset"]["dataUrl"].startswith("data:image/png;base64,")
    catalog = service.dispatch(
        "mobile.resources.assets.list",
        {"context": context(), "kind": "sticker", "offset": 0, "limit": 24},
    )
    assert catalog["total"] == 1
    assert catalog["assets"][0]["packId"] == "com.example.fixture"
    for field, value in (("offset", "later"), ("limit", 2.5), ("limit", True)):
        with pytest.raises(DomainError) as invalid_page:
            service.dispatch(
                "mobile.resources.assets.list",
                {
                    "context": context(),
                    "kind": "sticker",
                    "offset": 0,
                    "limit": 24,
                    field: value,
                },
            )
        assert invalid_page.value.code == "invalid_params"
    resolved = service.dispatch(
        "mobile.resources.asset.get",
        {
            "context": context(),
            "packId": "com.example.fixture",
            "assetId": "rain-sticker",
            "kind": "sticker",
        },
    )
    assert resolved["asset"]["dataUrl"].startswith("data:image/png;base64,")

    bob = character("card_b", "Bob")
    service.dispatch(
        "mobile.context.bind",
        {
            "context": context("card_b", "revision_b"),
            "activeCharacter": bob,
            "characters": [bob],
        },
    )
    assert service.dispatch(
        "mobile.appearance.get",
        {"context": context("card_b", "revision_b")},
    )["appearance"] == {
        "schemaVersion": 1,
        "preset": "modern",
        "tone": "midnight",
        "background": None,
    }

    alice = character()
    service.dispatch(
        "mobile.context.bind",
        {
            "context": context(),
            "activeCharacter": alice,
            "characters": [alice],
        },
    )
    service.dispatch(
        "mobile.resources.delete",
        {"context": context(), "packId": "com.example.fixture"},
    )
    fallback = service.dispatch("mobile.appearance.get", {"context": context()})
    assert fallback["appearance"]["background"] is None
    assert fallback["fallback"] == "background_missing"
